spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/appdb
    username: appuser
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8080
